### ISSUE TITLE
SetCVar - Combat protected function

### ISSUE THREAD

**Issue by c-hann** [AsphyxiaUI/AsphyxiaUI-Legion#1]
Move the both lines 
```
SetCVar( 'NamePlateVerticalScale', '1' )
SetCVar( 'NamePlateHorizontalScale', '1' )
```
from NamePlates.lua so Setup.lua into the table with other CVars. Avoids a taint at combat start with nameplates.

**Comment by AsphyxiaUI** [comment]
will be fixed with the next update. thanks
